dotenv: .env
networks:
  default: kovan
  rinkeby:
    verify: True
  mainnet-fork-dev:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  kovan:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
